server-port=25565
online-mode=false
difficulty=normal
gamemode=survival
max-players=20
view-distance=8
simulation-distance=6
level-name=world
motd=§aMinecraft Server §7| §bCrossplatform
enable-query=false
enable-rcon=false
spawn-protection=16
